[package]
name = "json-inspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
glob = "0.3.1"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
termion = "3.0.0"
regex = "1.10.4"

[workspace]
resolver = "2"
members = [
    "crates/ast",
]
