[package]
name = "json-inspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-inspector-ast = { path = "./crates/ast" }
json-inspector-json = { path = "./crates/json" }
getopts = "0.2"
glob = "0.3.1"
once_cell = "1.19.0"
regex = "1.10.4"

[workspace]
resolver = "2"
members = [
    "crates/ast",
    "crates/json"
]
