[package]
name = "i18n-locale-lint-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
i18n-locale-lint-ast = { path = "../ast" }
i18n-locale-lint-json = { path = "../json" }
i18n-locale-lint-yaml = { path = "../yaml" }
getopts = "0.2"
once_cell = "1.19.0"
regex = "1.10.4"
