[package]
name = "json-inspector-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
json-inspector-ast = { path = "../ast" }
json-inspector-json = { path = "../json" }
getopts = "0.2"
glob = "0.3.1"
once_cell = "1.19.0"
regex = "1.10.4"
