[package]
name = "json-inspector-json"
version = "0.0.1"
edition = "2021"

[dependencies]
json-inspector-ast = { path = "../ast" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
