[package]
name = "i18n-locale-lint-json"
version = "0.0.1"
edition = "2021"

[dependencies]
i18n-locale-lint-ast = { path = "../ast" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
